MatchZzic/MatchZzic/urls.py
from django.contrib import admin
from django.urls import path, include
from account import urls as account_url
from main import urls as main_url
from match import urls as match_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(account_url)),
    path('main/',include(main_url)),
    path('match/',include(match_url)),
]

MatchZzic/main/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.main, name='main'),
    path('match/', views.match, name='match')
]

MatchZzic/main/models.py
from django.db import models
from account.models import User

# Create your models here.

MatchZzic/main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import User

@login_required
def main(request):
    if request.method == 'POST':
        # 여행지 저장
        place = request.POST.get('place')
        user = request.session['user'] # 세션에서 user 가져옴/
        User.objects.filter(userId=user).update(travel_to=place)
        return redirect('match')
    else:
        user_id = request.session['user']
        user = User.objects.get(userId=user_id)
        return render(request, 'main.html', {'user': user})

def match(request):
    return render(request, 'match.html')

MatchZzic/main/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      #iphone-frame {
        width: 375px;
        height: 667px;
        border-radius: 30px;
        margin: 50px auto;
        position: relative;
        justify-content: center;
        align-items: center;
      }
      /* 상단로고 */
      .header {
        position: fixed;
        width: 322px;
        height: 405px;
        left: calc(50% - 322px / 2 + 0.5px);
        top: 4.5%;
      }
      .logo {
        position: absolute;
        font-family: "Inter";
        font-style: normal;
        font-weight: 800;
        font-size: 22.799px;
        line-height: 28px;
        color: rgba(26, 61, 255, 0.7);
      }
      .username {
        position: absolute;
        left: 80%;
        top: 10px;
        font-family: "Noto Sans KR";
        font-style: normal;
        font-weight: 500;
        font-size: 12px;
        line-height: 18px;
        color: rgba(114, 114, 114, 1);
      }
      .mypage_move {
        position: absolute;
        top: 2%;
        left: 95%;
      }
      iconify-icon {
        width: 22px;
        height: 22px;
      }
      /* 메인페이지 */

      .main_title {
        display: flex;
        flex-direction: column;
        justify-content: center;
      }
      .main_title img {
        position: absolute;
        width: 11.53px;
        left: calc(50% - 11.53px / 2 + 1.5px);
        /* top: 10%; */
        bottom: 85.16%;
      }
      .main_title .title {
        position: absolute;
        width: 138px;
        height: 29px;
        left: calc(50% - 138px / 2 + 0.5px);
        top: 108px;
        font-family: "Noto Sans KR";
        font-style: normal;
        font-weight: 700;
        font-size: 20px;
        line-height: 29px;
        text-align: center;
        color: #000000;
      }
      .main_title .title2 {
        /* 비슷한 타입의 사람과 여행가고 싶어요 */
        position: absolute;
        width: 114px;
        height: 30px;
        left: calc(50% - 114px / 2 + 0.5px);
        top: 151px;
        font-family: "Noto Sans KR";
        font-style: normal;
        font-weight: 700;
        font-size: 13px;
        line-height: 15px;
        text-align: center;
        color: #909090;
      }

      /* 메인페이지 여행가방 사진 */
      .main_img {
        position: absolute;
        width: 211px;
        height: 198px;
        left: calc(50% - 220px / 2 + 0.5px);
        top: 214px;
        background: #1a3dff;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
        border-radius: 20px;
      }

      .main_img img {
        position: absolute;
        width: 190px;
        height: 180px;
        left: calc(50% - 190px / 2 + 0.5px);
        top: 15px;
      }

      /* 동행할 여행지 입력란 */
      .main_input {
        display: flex;
        box-sizing: border-box;
        width: 279px;
        border-bottom: 0.833935px solid #dcdcdc;
        position: absolute;
        left: calc(50% - 72px / 2 - 90.99px);
        top: 452px;
        padding: 15px;
      }
      .main_input span {
        font-family: "Noto Sans KR";
        font-style: normal;
        font-weight: 500;
        font-size: 12.509px;
        line-height: 18px;
        color: #000000;
      }

      .main_input input {
        position: absolute;
        width: 135px;
        height: 24px;
        left: 130px;

        font-family: "Noto Sans KR";
        font-style: normal;
        font-weight: 500;
        font-size: 10px;
        line-height: 14px;
        color: rgba(57, 57, 57, 0.4);

        background: #ffffff;
        box-shadow: 0px 0px 4px rgba(0, 0, 0, 0.5);
        border-radius: 10px;
        border: none;
        text-align: center;
      }

      .main_input input:focus {
        background: #ffffff;
        box-shadow: 0px 0px 4px #1a3dff;
        color: rgba(26, 61, 255, 0.64);
        border: none;
        outline: none;
      }

      input[type="submit"] {
        position: absolute;
        width: 217px;
        height: 46px;
        left: calc(50% - 217px / 2);
        top: 543px;

        background: #5e77fe;
        border-radius: 15px;
        border: none;

        font-family: "Noto Sans KR";
        font-style: normal;
        font-weight: 700;
        font-size: 16px;
        line-height: 23px;
        text-align: center;
        color: #ffffff;
      }
    </style>
    <!-- <link rel="stylesheet" href="{% static 'css/main2.css' %}" /> -->
  </head>
  <body>
    <div id="iphone-frame">
      <!-- 상단 로고  -->
      <div class="header">
        <div class="logo">MatchZzic</div>
        <div class="username">{{user}}</div>
        <div class="mypage_move">
          <a href="{% url 'mypage' %}">
            <iconify-icon
              icon="octicon:feed-person-16"
              style="color: #5e77fe"
            ></iconify-icon
          ></a>
        </div>
      </div>

      <!-- 메인 페이지 타이틀 -->
      <div class="main_title">
        <img src="{% static 'image/Mask group4.png' %}" alt="" />
        <span class="title">동행매칭 서비스</span>
        <span class="title2">비슷한 타입의 사람과 <br />여행가고 싶어요</span>
      </div>

      <!-- 메인 페이지 여행가방 사진 -->
      <div class="main_img">
        <img src="{% static 'image/여행 아이콘3.png' %}" alt="" />
      </div>

    <form method="POST" action="{% url 'main_app:main' %}">
      {% csrf_token %}
      <!-- 동행할 여행지 입력란 -->
      <div class="main_input">
        <span> 동행할 여행지</span>
        <input type="text" placeholder="여행지를 입력해주세요" name="place"/>
      </div>

      <!-- 지금동행찾기 버튼 -->
      <input type="submit" value="지금 동행 찾기" />
    </form>

    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
  </body>
</html>